name: Build

on:
  push:
    paths:
      - ton-repo-version.txt

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: duelistdev/ton-sites-proxy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version
        id: vars
        run: |
          echo "TON_REPO_VERSION=$(cat ton-repo-version.txt)"
          echo "TON_REPO_VERSION=$(cat ton-repo-version.txt)" >> $GITHUB_ENV


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ env.TON_REPO_VERSION }}
            ${{ env.DOCKER_REPO }}:latest
          build-args: |
            TON_REPO_VERSION=${{ env.TON_REPO_VERSION }}
